export const lightTheme = {

    body: '#e9e9ef',
    text: '#4c4cff',
    ingridientTextBox: '#030303',
    toggleBorder: '#FFF',
    background: '#e9e9ef',
    backgroundWrapper: '#4c4cff',
    backgroundToogle: '#e9e9ef',
    headerText: '#F2F2F3',
    hoverText: '#aeaeee',
    disabledButton: '#7c7cdc',
    disabledColor: '#dad3d3',
    backgroundCart: '#a3bcf6',
    modal: '#c4c4eb',
    colorOrder: '#fff',
    titleOrder: '#4C4CFF',
    priceImg: '#4C4CFF',
    modalWindow: '#8585AD',
    menuColorImg: '#8585AD',
    hoverTextNavbar: '#a0a0c8',
    statusCardOrder: '#229869',
    hoverCardOrder: '#b7cbfa',
    feedStaticTitle: '#8585AD',
    feedStaticOrderStatus: '#030303',
    backgroundWindow: '#e9e9ef',
    dinamicPathTitle: '#4c4cff',
    dinamicCompountOrder: '#030303',
    buttonProfile: '#e9e9ef',
    buttonHoverProfile: '#64646e',
    buttonActive: '#64646e',
    inputActive: '#fff',
    menuClose: '#4c4cff'
}
    
export const darkTheme = {

    body: '#131316',
    text: '#fff',
    ingridientTextBox: '#fff',
    toggleBorder: '#6B8096',
    background: '#131316',
    backgroundWrapper: '#1C1C21',
    backgroundToogle: '#282838',
    headerText: '#8585AD',
    hoverText: '#F2F2F3',
    disabledButton: '#3A3A55',
    disabledColor: '#8585AD',
    backgroundCart: '#1C1C21',
    modal: '#1C1C21',
    colorOrder: '#fff',
    titleOrder: '#fff',
    priceImg: '#fff',
    modalWindow: '#F2F2F3',
    menuColorImg: '#fff',
    hoverTextNavbar: '#F2F2F3',
    statusCardOrder: '#00CCCC',
    hoverCardOrder: '#2F2F37',
    feedStaticTitle: '#f2f2f3',
    feedStaticOrderStatus: '#f2f2f3',
    backgroundWindow: '#000',
    dinamicPathTitle: '#f2f2f3',
    dinamicCompountOrder: '#f2f2f3',
    buttonProfile: '#131316',
    buttonHoverProfile: '#F2F2F3',
    buttonActive: 'F2F2F3',
    inputActive: '#fff',
    menuClose: '#F2F2F3'
}