


interface IIllustration {
  id: number,
  largePhoto: string,
  normalPhoto: string,
  mobilePhoto: string,
  previewPhoto: string,
  price: number,
  nameItem: string,
  type: string,
  amount: number,
}



export const harcodeIllustration: IIllustration[] = [
  {
    id: 0,
    largePhoto: "/illustration/crator/cratorLarge.png",
    normalPhoto: "/illustration/crator/cratorMobile.png",
    mobilePhoto: "/illustration/crator/cratorNormal.png",
    previewPhoto: "/illustration/crator/cratorPreview.png",
    price: 30,
    nameItem: "Краторная булка N-200i",
    type: "Булки",
    amount: 2,
  },
  {
    id: 1,
    largePhoto: "/illustration/bun/bunLarge.png",
    normalPhoto: "/illustration/bun/bunNormal.png",
    mobilePhoto: "/illustration/bun/bunMobile.png",
    previewPhoto: "/illustration/bun/bunPreview.png",
    price: 20,
    nameItem: "Флюоресцентная булка R2-D3",
    type: "Булки",
    amount: 1,
  },
  {
    id: 2,
    largePhoto: "/illustration/file/fileLarge.png",
    normalPhoto: "/illustration/file/fileNormal.png",
    mobilePhoto: "/illustration/file/fileMobile.png",
    previewPhoto: "/illustration/file/filePreview.png",
    price: 300,
    nameItem: "Филе Люминесцентного тетраодонтимформа",
    type: "Начинки",
    amount: 1,
  },
  {
    id: 3,
    largePhoto: "/illustration/meat/meatLarge.png",
    normalPhoto: "/illustration/meat/meatNormal.png",
    mobilePhoto: "/illustration/meat/meatMobile.png",
    previewPhoto: "/illustration/meat/meatPreview.png",
    price: 300,
    nameItem: "Мясо бессмертных моллюсков Protostomia",
    type: "Начинки",
    amount: 2,
  },
  {
    id: 4,
    largePhoto: "/illustration/meteorite/meteoriteLarge.png",
    normalPhoto: "/illustration/meteorite/meteoriteNormal.png",
    mobilePhoto: "/illustration/meteorite/meteoriteMobile.png",
    previewPhoto: "/illustration/meteorite/meteoritePreview.png",
    price: 300,
    nameItem: "Говяжий метеорит (отбивная)",
    type: "Начинки",
    amount: 1,
  },
  {
    id: 5,
    largePhoto: "/illustration/bioCutlet/bioCutletLarge.png",
    normalPhoto: "/illustration/bioCutlet/bioCutletNormal.png",
    mobilePhoto: "/illustration/bioCutlet/bioCutletMobile.png",
    previewPhoto: "/illustration/bioCutlet/bioCutletPreview.png",
    price: 300,
    nameItem: "Биокотлета из марсианской Магнолии",
    type: "Начинки",
    amount: 1,
  },
  {
    id: 6,
    largePhoto: "/illustration/sauce/sauceLarge.png",
    normalPhoto: "/illustration/sauce/sauceNormal.png",
    mobilePhoto: "/illustration/sauce/sauceMobile.png",
    previewPhoto: "/illustration/sauce/saucePreview.png",
    price: 30,
    nameItem: "Соус Spicy-X",
    type: "Соусы",
    amount: 1,
  },
  {
    id: 7,
    largePhoto: "/illustration/spiceSauce/spiceSauceLarge.png",
    normalPhoto: "/illustration/spiceSauce/spiceSauceNormal.png",
    mobilePhoto: "/illustration/spiceSauce/spiceSauceMobile.png",
    previewPhoto: "/illustration/spiceSauce/spiceSaucePreview.png",
    price: 30,
    nameItem: "Соус фирменный Space Sauce",
    type: "Соусы",
    amount: 3,
  },
  {
    id: 8,
    largePhoto: "/illustration/space/spaceLarge.png",
    normalPhoto: "/illustration/space/spaceNormal.png",
    mobilePhoto: "/illustration/space/spaceMobile.png",
    previewPhoto: "/illustration/space/spacePreview.png",
    price: 30,
    nameItem: "Соус традиционный галактический",
    type: "Соусы",
    amount: 2,
  },
  {
    id: 9,
    largePhoto: "/illustration/traditionalSauce/traditionalSauceLarge.png",
    normalPhoto: "/illustration/traditionalSauce/traditionalSauceNormal.png",
    mobilePhoto: "/illustration/traditionalSauce/traditionalSauceMobile.png",
    previewPhoto: "/illustration/traditionalSauce/traditionalSaucePreview.png",
    price: 30,
    nameItem: "Соус с шипами Антарианского плоскоходца",
    type: "Соусы",
    amount: 1,
  },
  {
    id: 10,
    largePhoto: "/illustration/fruit/fruitLarge.png",
    normalPhoto: "/illustration/fruit/fruitNormal.png",
    mobilePhoto: "/illustration/fruit/fruitMobile.png",
    previewPhoto: "/illustration/fruit/fruitPreview.png",
    price: 80,
    nameItem: "Плоды фалленианского дерева",
    type: "Начинки",
    amount: 1,
  },
  {
    id: 11,
    largePhoto: "/illustration/crystals/crystalsLarge.png",
    normalPhoto: "/illustration/crystals/crystalsNormal.png",
    mobilePhoto: "/illustration/crystals/crystalsMobile.png",
    previewPhoto: "/illustration/crystals/crystalsPreview.png",
    price: 80,
    nameItem: "Кристаллы марсианских альфа-сахаридов",
    type: "Начинки",
    amount: 1,
  },
  {
    id: 12,
    largePhoto: "/illustration/mineral/mineralLarge.png",
    normalPhoto: "/illustration/mineral/mineralNormal.png",
    mobilePhoto: "/illustration/mineral/mineralMobile.png",
    previewPhoto: "/illustration/mineral/mineralPreview.png",
    price: 80,
    nameItem: "Хрустящие минеральные кольца",
    type: "Начинки",
    amount: 2,
  },
  {
    id: 13,
    largePhoto: "/illustration/salad/saladLarge.png",
    normalPhoto: "/illustration/salad/saladNormal.png",
    mobilePhoto: "/illustration/salad/saladMobile.png",
    previewPhoto: "/illustration/salad/saladPreview.png",
    price: 80,
    nameItem: "Мини-салат Экзо-Плантаго",
    type: "Начинки",
    amount: 1,
  },
  {
    id: 14,
    largePhoto: "/illustration/cheese/cheeseLarge.png",
    normalPhoto: "/illustration/cheese/cheeseNormal.png",
    mobilePhoto: "/illustration/cheese/cheeseMobile.png",
    previewPhoto: "/illustration/cheese/cheesePreview.png",
    price: 80,
    nameItem: "Сыр с астероидной плесенью",
    type: "Начинки",
    amount: 1,
  },
];
